[package]
name = "node_resolve"
version = "0.1.0"
authors = ["The Deno Authors"]
default-run = "deno"
edition = "2021"
license = "MIT"
repository = "https://github.com/denoland/node_resolve"
description = "The Node.js module resolution algorithm"

[dependencies]
